# Matrices is Python

## Numpy arrays revision

Do you remember how Numpy arrays work in Python? Here's a quick reminder:
 
Having imported Numpy as `np` you can create a Numpy array with the `np.array` function.

In [1]:
import numpy as np
x = np.array([10, 9, 8, 7])

In [2]:
print(x)

[10  9  8  7]


Once created, you can access individual entries using brackets. Remember that the indexing starts from `0`, so for an array with `n` entries, the first entry will have index `0` and the last entry will have index `n-1`:

In [3]:
print(x[0])
print(x[1])
print(x[3])

10
9
7


Indexing also works backwards, so you can (also) access the last entry with index -1, and so on.

In [4]:
print(x[-1])
print(x[-2])

7
8


An important property of Numpy arrays is that we can use arithmetic operations on them. Like this:

In [5]:
x = np.array([10, 9, 8, 7])
y = np.array([1, 1, -1, -1])
print(x+y)
print(2*y)
print(x*y)

[11 10  7  6]
[ 2  2 -2 -2]
[10  9 -8 -7]


Note that all arithmetic operations are done on the corresponding entries, e.g. the `k`th entry of `x*y` is the `k`th entry of `x` times the `k`th entry of `y`. Also, note that this is *not* how matrix multiplication works.

## Matrices
In Python, a matrix is simply an *array of arrays*. Each entry represents a row, which in itself is an array. So, to define the matrices
$$A=\begin{bmatrix}1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix},\quad 
B=\begin{bmatrix}1 & 1\\ -1 & -1\end{bmatrix},\quad
C=\begin{bmatrix}-1 & -2\\ -3 & -4\end{bmatrix},$$
we can do like this:

In [6]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,1],[-1,-1]])
C = np.array([[-1,-2],[-3,-4]])
print(A)
print(B)
print(C)

[[1 2 3]
 [4 5 6]]
[[ 1  1]
 [-1 -1]]
[[-1 -2]
 [-3 -4]]


Note that for example the first entry of the array `A` is the *array* `[1,2,3]`.

Now, if we think of `A` as a *matrix* and we want to access the entry of row $2$, colum $3$ of `A`, we could use the fact that it's the third entry of the second entry of `A`, i.e. (remembering that indexing starts from zero):

In [7]:
A[1][2]

6

Fortunately, Python also allows the slightly more intuitive notation:

In [8]:
A[1,2]

6

We have seen above that for Numpy arrays, addition (`+`) of arrays and multiplication (`*`) with scalar works element-wise, so we can use these operations to calculate matrix sums and the product of a matrix with a scalar. 
Recall that we have already defined:
$$A=\begin{bmatrix}1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix},\quad 
B=\begin{bmatrix}1 & 1\\ -1 & -1\end{bmatrix},\quad
C=\begin{bmatrix}-1 & -2\\ -3 & -4\end{bmatrix},$$
so let's calculate $B+C$ and $2A$:

In [14]:
print(B+C)
print(2*A)

[[ 0 -1]
 [-4 -5]]
[[ 2  4  6]
 [ 8 10 12]]


But with matrix multiplication we have to watch out. The `*` works-element wise, i.e:

In [10]:
print("B=",B)
print("C=",C)
print("The Python operation B*C, gives us the result:")
print(B*C)

B= [[ 1  1]
 [-1 -1]]
C= [[-1 -2]
 [-3 -4]]
The Python operation B*C, gives us the result:
[[-1 -2]
 [ 3  4]]


The result above is obained by multiplying each element of $B$ with the corresponding element of $C$ (please check) but that is *not* the matrix product $BC$.

Instead, to evaluate a matrix product, there are a few ways:
- You can use the `np.matmul()` function.
- You can use the `@` operator.
Both alternatives allow you to calculate matrix products, as illustrated below.

In [11]:
np.matmul(B,C)

array([[-4, -6],
       [ 4,  6]])

In [12]:
B @ C

array([[-4, -6],
       [ 4,  6]])

This is indeed the matrix product $BC$ (please check!).

Let's try it some more. One of the following cells will produce an error. *Try to predict which one before running the cells*. 

In [15]:
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [16]:
B@A

array([[ 5,  7,  9],
       [-5, -7, -9]])

In [17]:
np.matmul(B,A)

array([[ 5,  7,  9],
       [-5, -7, -9]])