# AE 2 - Network 3

To save you some work, here is the matrix for Network 3, i.e.
$$M=\begin{bmatrix}
0 & 1/2 & 1/2 & 1/2 & 0 & 0\\
1/2 & 0 & 1/2 & 0 & 0 & 0\\
1/2 & 1/2 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1/2 & 0 & 1\\
0 & 0 & 0 & 0 & 1 & 0
\end{bmatrix}.$$

In [4]:
import numpy as np
M = np.array([[0,0.5,0.5,0.5,0,0],[0.5,0,0.5,0,0,0],[0.5,0.5,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0.5,0,1],[0,0,0,0,1,0]])
print(M)

[[0.  0.5 0.5 0.5 0.  0. ]
 [0.5 0.  0.5 0.  0.  0. ]
 [0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  1. ]
 [0.  0.  0.  0.  1.  0. ]]


In [13]:
np.linalg.matrix_power(M,6)

array([[0.34375 , 0.328125, 0.328125, 0.15625 , 0.      , 0.      ],
       [0.328125, 0.34375 , 0.328125, 0.171875, 0.      , 0.      ],
       [0.328125, 0.328125, 0.34375 , 0.171875, 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      , 1.      , 0.      ],
       [0.      , 0.      , 0.      , 0.5     , 0.      , 1.      ]])

As usual, you might want to experiment with some random surfers, such as

In [65]:
p = np.array([[100],[100],[100],[100],[100],[100]])

and see what happens when you repeat the formula:

In [64]:
p = np.matmul(M,p)
print(p)

[[350.00000037]
 [349.99999981]
 [349.99999981]
 [  0.        ]
 [450.        ]
 [300.        ]]


And you might be interested in eigenvectors with eigenvalue 1.

In [14]:
l,P = np.linalg.eig(M)

In [15]:
print(np.round(l,2))

[-0.5  1.  -0.5  1.  -1.   0. ]


In [16]:
print(np.round(P,2))

[[-0.82  0.58  0.19  0.    0.    0.35]
 [ 0.41  0.58 -0.78  0.    0.   -0.35]
 [ 0.41  0.58  0.59  0.    0.   -0.35]
 [ 0.    0.    0.    0.    0.    0.71]
 [ 0.    0.    0.    0.71  0.71  0.  ]
 [ 0.    0.    0.    0.71 -0.71 -0.35]]


For the second part of this exercise (involving the Google matrix), the following matrix might be useful:

In [66]:
V = 1/6*np.ones((6,6))
print(V)

[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


The last calculations, you can do yourself:

In [84]:
G = 0.15*V + 0.85*M
print(G)

[[0.025 0.45  0.45  0.45  0.025 0.025]
 [0.45  0.025 0.45  0.025 0.025 0.025]
 [0.45  0.45  0.025 0.025 0.025 0.025]
 [0.025 0.025 0.025 0.025 0.025 0.025]
 [0.025 0.025 0.025 0.45  0.025 0.875]
 [0.025 0.025 0.025 0.025 0.875 0.025]]


In [85]:
np.linalg.matrix_power(G,6)

array([[0.25162798, 0.24573502, 0.24573502, 0.18091245, 0.12198283,
        0.12198283],
       [0.23817549, 0.24406845, 0.23817549, 0.17924588, 0.11442331,
        0.11442331],
       [0.23817549, 0.23817549, 0.24406845, 0.17924588, 0.11442331,
        0.11442331],
       [0.025     , 0.025     , 0.025     , 0.025     , 0.025     ,
        0.025     ],
       [0.12765629, 0.12765629, 0.12765629, 0.12765629, 0.50480581,
        0.12765629],
       [0.11936474, 0.11936474, 0.11936474, 0.3079395 , 0.11936474,
        0.49651426]])

In [87]:
print(np.round(l,2))

[ 1.    0.85 -0.   -0.85 -0.43 -0.43]


In [88]:
print(np.round(P,2))

[[-0.45  0.37  0.35 -0.   -0.82 -0.31]
 [-0.43  0.37 -0.35  0.    0.41 -0.5 ]
 [-0.43  0.37 -0.35 -0.    0.41  0.81]
 [-0.06 -0.    0.71  0.   -0.   -0.  ]
 [-0.47 -0.55  0.   -0.71 -0.    0.  ]
 [-0.46 -0.55 -0.35  0.71 -0.   -0.  ]]


In [82]:
O = np.matmul(M,O)
print(O)

[[0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.71]
 [0.71]]
