# AE 2 - Network 1

To save you some work, here is the matrix $M$ from the first exercise.

In [188]:
import numpy as np
M = np.array([[0,1/3,1,1/2,0],[1/3,0,0,0,0],[0,1/3,0,0,1],[1/3,0,0,0,0],[1/3,1/3,0,1/2,0]])

If you want to calculate an integer power of $M$ you can do it like this. Below we have calculated $M^2$:

In [192]:
np.linalg.matrix_power(M,6)

array([[0.37328532, 0.34876543, 0.24691358, 0.34567901, 0.35493827],
       [0.08230453, 0.1196845 , 0.11831276, 0.10545267, 0.14814815],
       [0.28120713, 0.22530864, 0.27469136, 0.27623457, 0.12345679],
       [0.08230453, 0.1196845 , 0.11831276, 0.10545267, 0.14814815],
       [0.18089849, 0.18655693, 0.24176955, 0.16718107, 0.22530864]])

If you want to experiment with some random surfers, you can start with some initial population, e.g.

In [171]:
p = np.array([[400],[100],[100],[100],[100]])

(Please feel free to try some other initial `p`).

Then you can calculate the recursive sequence $\mathbf{p}_j=M\mathbf{p}_{j-1}$, simply by repeatedly running the cell below, over and over, and observe how its output changes (and how it converges).

In [179]:
p = np.matmul(M,p)
print(p)

[[259.28593202]
 [ 90.28444597]
 [192.37635269]
 [ 90.28444597]
 [167.76882335]]


Alternatively (or both) you might alse want to calculate the eigenvectors of $M$ with eigenvalue 1. To get the eigenvalues and eigenvectors we can run

In [18]:
l,P = np.linalg.eig(M)
print("Eigenvalues = \n",np.round(l,2),"\n")
print("Corresponging basis vectors for eigenspace = \n",np.round(P,2))

Eigenvalues = 
 [ 1.  +0.j   -0.21+0.66j -0.21-0.66j -0.58+0.j   -0.  +0.j  ] 

Corresponging basis vectors for eigenspace = 
 [[-0.69+0.j   -0.05-0.58j -0.05+0.58j -0.76+0.j   -0.  +0.j  ]
 [-0.23+0.j   -0.26+0.11j -0.26-0.11j  0.44+0.j   -0.8 +0.j  ]
 [-0.5 +0.j    0.61+0.j    0.61-0.j    0.08+0.j   -0.  +0.j  ]
 [-0.23+0.j   -0.26+0.11j -0.26-0.11j  0.44+0.j    0.53+0.j  ]
 [-0.42+0.j   -0.04+0.37j -0.04-0.37j -0.19+0.j    0.27+0.j  ]]


The above tells us that the eigenspace associated with the eigenvalue 1 is:

$$\mathbf{x}\approx t(0.69,0.23,0.5,0.23,0.42),\quad t\in\mathbb{R}.$$

(we could multiply the given basis vector with -1, because anyway the eigenspace consists of all *multiples* of the same vector).

In [116]:
N = np.array([[-0.69],[-0.23],[-0.5],[-0.23],[-0.42]])

In [180]:
a = a/sum(a)

In [184]:
a = 200*a

In [185]:
a

array([[33413.84863124],
       [11111.11111111],
       [23993.55877617],
       [11111.11111111],
       [20370.37037037]])