In [1]:
import numpy as np

In [2]:
M = np.array([[0,1/3,1,1/2,0],[1/3,0,0,0,0],[0,1/3,0,0,1],[1/3,0,0,0,0],[1/3,1/3,0,1/2,0]])
p = np.array([[100],[100],[100],[100],[100]])
print("M=\n",M)
print("p=\n",p)

M=
 [[0.         0.33333333 1.         0.5        0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         1.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.5        0.        ]]
p=
 [[100]
 [100]
 [100]
 [100]
 [100]]


In [13]:
p = M@p
print(p)

[[165.67882183]
 [ 55.3050221 ]
 [122.02884469]
 [ 55.3050221 ]
 [101.68228929]]


In [15]:
l,P = np.linalg.eig(M)

In [16]:
l

array([ 1.00000000e+00+0.j        , -2.09845283e-01+0.65926989j,
       -2.09845283e-01-0.65926989j, -5.80309435e-01+0.j        ,
       -5.38991039e-18+0.j        ])

In [6]:
np.round(P,2)

array([[-0.69+0.j  , -0.05-0.58j, -0.05+0.58j, -0.76+0.j  , -0.  +0.j  ],
       [-0.23+0.j  , -0.26+0.11j, -0.26-0.11j,  0.44+0.j  , -0.8 +0.j  ],
       [-0.5 +0.j  ,  0.61+0.j  ,  0.61-0.j  ,  0.08+0.j  , -0.  +0.j  ],
       [-0.23+0.j  , -0.26+0.11j, -0.26-0.11j,  0.44+0.j  ,  0.53+0.j  ],
       [-0.42+0.j  , -0.04+0.37j, -0.04-0.37j, -0.19+0.j  ,  0.27+0.j  ]])

In [ ]:
x=P[:,0]

In [ ]:
x = x/sum(x)

In [ ]:
500*x