# AE 2 - Network 2

To save you some work, here are the three suggested matrices from the exercise:

In [29]:
import numpy as np
M1 = np.array([[0,1/3,0,1/2,0],[1/3,0,0,0,0],[0,1/3,0,0,1],[1/3,0,0,0,0],[1/3,1/3,0,1/2,0]])
print(M1)

[[0.         0.33333333 0.         0.5        0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         1.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.5        0.        ]]


In [65]:
M2 = M1.copy()
M2[:,2]=np.array([0,0,1,0,0])
print(M2)

[[0.         0.33333333 0.         0.5        0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.         0.33333333 1.         0.         1.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.5        0.        ]]


In [66]:
M3 = M1.copy()
M3[:,2]=np.array([0.2,0.2,0.2,0.2,0.2])
print(M3)

[[0.         0.33333333 0.2        0.5        0.        ]
 [0.33333333 0.         0.2        0.         0.        ]
 [0.         0.33333333 0.2        0.         1.        ]
 [0.33333333 0.         0.2        0.         0.        ]
 [0.33333333 0.33333333 0.2        0.5        0.        ]]


If you want to experiment with some random surfers, you can start with some initial population, e.g.

In [99]:
p = np.array([[100],[100],[100],[100],[100]])

 and try repeating the formulas below.
 **I recommend resetting `p` above between experiments, or it might get confusing.**

In [87]:
# Experiment with M1
p = np.matmul(M1,p)
print(np.round(p,2))

[[ 44.47]
 [ 34.43]
 [154.4 ]
 [ 34.43]
 [ 78.9 ]]


In [84]:
# Experiment with M2
p = np.matmul(M2,p)
print(np.round(p,2))

[[1.7000e-01]
 [1.7000e-01]
 [4.9917e+02]
 [1.7000e-01]
 [3.3000e-01]]


In [114]:
# Experiment with M3
p = np.matmul(M3,p)
print(p)

[[ 86.84321731]
 [ 63.15727158]
 [171.05237911]
 [ 63.15727158]
 [115.78986042]]


Alternatively you might want to calculate the eigenvalues and eigenvectors.

In [92]:
l1, P1= np.linalg.eig(M1)
l2, P2= np.linalg.eig(M2)
l3, P3= np.linalg.eig(M3)

In [93]:
print(np.round(l1,2))

[ 0.    0.    0.53 -0.53  0.  ]


In [94]:
print(np.round(l2,2))

[ 1.    0.    0.53 -0.53  0.  ]


In [95]:
print(np.round(P2,2))

[[ 0.    0.    0.23  0.72  0.  ]
 [ 0.    0.    0.14 -0.45  0.  ]
 [ 1.   -0.71 -0.88 -0.07 -0.71]
 [ 0.    0.    0.14 -0.45 -0.  ]
 [ 0.    0.71  0.37  0.26  0.71]]


In [96]:
print(np.round(l3,2))

[ 1.  +0.j  -0.51+0.j  -0.14+0.3j -0.14-0.3j -0.  +0.j ]


In [97]:
print(np.round(P3,2))

[[ 0.36+0.j    0.74+0.j   -0.34-0.06j -0.34+0.06j -0.  +0.j  ]
 [ 0.26+0.j   -0.42+0.j   -0.12-0.11j -0.12+0.11j -0.8 +0.j  ]
 [ 0.71+0.j   -0.17+0.j    0.83+0.j    0.83-0.j    0.  +0.j  ]
 [ 0.26+0.j   -0.42+0.j   -0.12-0.11j -0.12+0.11j  0.53+0.j  ]
 [ 0.48+0.j    0.26+0.j   -0.24+0.28j -0.24-0.28j  0.27+0.j  ]]
